course/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predictapp.urls')),
]

predictapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'predictapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
    path('database/', views.database, name='db'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

predictapp/models.py
from django.db import models


# Create your models here.
class Record(models.Model):
    gender = models.CharField(max_length=20)
    grade = models.IntegerField()
    openness = models.IntegerField()
    agreeableness = models.IntegerField()
    emotions = models.IntegerField()
    conscientiousness = models.IntegerField()
    extraversion = models.IntegerField()
    course = models.CharField(max_length=30)

    def __str__(self):
        return self.course

predictapp/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Record

# TO DO:::
# Install pandas & sklearn

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import pickle



# Create your views here.
def index(request):
    return render(request, 'predictapp/index.html')


def database(request):
    records = Record.objects.all()
    paginator = Paginator(records, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'predictapp/db.html', {'records': records, 'page_obj': page_obj})


def predict(request):
    if request.method == 'POST':
        gender = request.POST.get('gender')   
        grade = request.POST.get('grade')
        openness = int(request.POST.get('openness'))
        agreeableness = int(request.POST.get('agreeableness'))
        emotions = int(request.POST.get('emotions'))
        conscientiousness = int(request.POST.get('conscientiousness'))
        extraversion = int(request.POST.get('extraversion'))

    # TO DO:::
    # Switch case the grade to have numeric values
        if grade == 'A':
            grade = 80
        elif grade == 'A-':
            grade = 75    
        elif grade == 'B+':
            grade = 70
        elif grade == 'B':
            grade = 65
        elif grade == 'B-':
            grade = 60    
        elif grade == 'C+':
            grade = 55
        elif grade == 'C':
            grade = 50
        elif grade == 'C-':
            grade = 45        
        elif grade == 'D+':
            grade = 40
        elif grade == 'D':
            grade = 30
        elif grade == 'D-':
            grade = 20
        else:
            grade = 10
      

        # Load the model & unpickle
        with open('/home/code/Projects/ML/Course/courses_pickle', 'rb') as f:
            md = pickle.load(f)
    

            # Predict & return the results   
            course = md.predict([ [gender, grade, openness, agreeableness, emotions, conscientiousness, extraversion] ])[0] #Pass the values from the form
        
            record = Record(gender=gender, grade=grade, openness=openness, agreeableness=agreeableness, emotions=emotions, conscientiousness=conscientiousness, extraversion=extraversion, course=course)
            record.save()
        
        return render(request, 'predictapp/index.html',
            {
                'gender': gender,
                'grade': grade,
                'openness': openness,
                'agreeableness': agreeableness,
                'emotions': emotions,
                'conscientiousness': conscientiousness,
                'extraversion': extraversion,
                'course': course
            })
    return redirect('predictapp:index')    

predictapp/templates/predictapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'predictapp/css/style.css' %}">
</head>

<body>
    <nav>
        <div class="container">
            <h2 class="brand">
                <a href="{% url 'predictapp:index' %}">Courses</a>
            </h2>
            <ul class="nav-links">
                <li>
                    <a href="{% url 'predictapp:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'predictapp:db' %}">Database</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}{% endblock %}
</body>

</html>

predictapp/templates/predictapp/db.html
{% extends 'predictapp/base.html' %}

{% load static %}

{% block title %}Database{%endblock %}

{% block content %}

<style>
    table {
        border-collapse: collapse;
        width: 100%;
        margin: 1rem 0;
        text-align: center;
    }

    table td,
    table th {
        border: 1px solid rgb(19, 18, 18);
        padding: 8px;
    }

    table tr:nth-child(even) {
        background-color: #e2dada;
    }

    table tr:hover {
        background-color: #ddd;
    }

    table th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #054b46;
        color: white;
        text-align: center;
    }
</style>

<div class="container">
    {% if records %}

    <table class="table">
        <thead>
            <th>#</th>
            <th>Grade Score</th>
            <th>Gender</th>
            <th>Openness</th>
            <th>Agreeableness</th>
            <th>Emotions</th>
            <th>Conscientiousness</th>
            <th>Extraversion</th>
            <th>Predicted Course</th>
        </thead>
        <tbody>
            {% for record in records %}
            <tr>
                <td>{{record.pk}}</td>
                <td>{{record.grade}}</td>
                <td>{{ record.gender }}</td>
                <td>{{record.openness}}</td>
                <td>{{record.agreeableness}}</td>
                <td>{{record.emotions}}</td>
                <td>{{record.conscientiousness}}</td>
                <td>{{record.extraversion}}</td>
                <td>{{record.course}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div> -->
    {% endif %}
</div>

{% endblock %}

predictapp/templates/predictapp/index.html
{% extends 'predictapp/base.html' %}

    {% block title %}Courses {% endblock %}

    {% block content %}
    <main>
        <div class="container">
            <section class="input">
                <div class="header">
                    <h2>Get Course suggestion</h2>
                </div>

                <form action="{% url 'predictapp:predict' %}" method="POST">
                    {% csrf_token %}
                    <select name="gender">
                        <option value="1" name="male">Male</option>
                        <option value="0" name="female">Female</option>
                    </select>

                    <!-- TO DO::::: Input type for decimal -->
                    <input type="text" name="grade" placeholder="Grade..." required>
                    <input type="number" name="openness" placeholder="Openness..." required>
                    <input type="number" name="agreeableness" placeholder="Agreeableness..." required>
                    <input type="number" name="emotions" placeholder="Emotional stability..." required>
                    <input type="number" name="conscientiousness" placeholder="Conscientiousness..." required>
                    <input type="number" name="extraversion" placeholder="Extraversion..." required>

                    <button type="submit" class="btn">Submit</button>    
                </form>
            </section>

            <section class="output">
                    <div class="header">
                        <h1>Suggestion Results</h1>
                    </div>
                    <div class="card">
                        <div class="input-data">
                            <h3>Submitted Data</h3>
                            <p><strong>Grade Score:&nbsp;</strong>
                                {{ grade }}
                            </p>
                            <p><strong>Gender:&nbsp;</strong>{% if gender == 1 %}Male {% else %} Female {% endif %}</p>
                            <p><strong>Openness:&nbsp;</strong>{{ openness }}</p>
                            <p><strong>Agreeableness:&nbsp;</strong>{{ agreeableness }}</p>
                            <p><strong>Emotions:&nbsp;</strong>{{ emotions }}</p>
                            <p><strong>Conscientiousness:&nbsp;</strong>{{ conscientiousness }}</p>
                            <p><strong>Extraversion:&nbsp;</strong>{{ extraversion }}</p>
                        </div>

                        <div class="output-data">
                            <h3>Suggested Course</h3>
                            <h3 class="result">{{ course }}</h3>
                        </div>
                    </div>
                </div>

            </section>
        </div>
    </main>
{% endblock %}